"""The experiments the application manages, and where they live.

An experiment is a folder in the shape the pipeline already uses — `input/`,
`output/`, `experiment.toml` — so an experiment **is** a workspace. What this
module adds is a place to keep several of them and a way to make one without
opening a file manager.

    <user_data_dir>/chatlens/experiments/
        coalition-formation/
            experiment.toml
            input/
            output/
        ultimatum-2026/
            ...

The root is the application's own data directory, not the folder the package
was installed into: `uv tool install` rewrites that one from scratch on every
upgrade, and an experiment kept there would be destroyed by the first update.
It can be moved with `--library` or `CHATLENS_LIBRARY` for anyone who wants
their experiments on a shared drive, and `--workspace` still points at a single
folder anywhere for anyone who keeps their own.

Every path here is built from a **slug** we generate, never from text that
arrives from the browser, and every path is checked to fall inside the root
before it is used. The name the researcher types is kept in `experiment.toml`,
where it can be anything.
"""

from __future__ import annotations

import os
import re
import unicodedata
from datetime import datetime
from pathlib import Path

from . import config

FOLDER = 'experiments'
ARCHIVED = '.archived'

# What a folder name may contain. Everything else is transliterated or dropped.
SLUG_SAFE = re.compile(r'[^a-z0-9]+')

# Names Windows refuses whatever the extension, which would make an experiment
# impossible to create on a machine we support.
RESERVED = {
    'con', 'prn', 'aux', 'nul',
    *(f'com{i}' for i in range(1, 10)),
    *(f'lpt{i}' for i in range(1, 10)),
}


class LibraryError(RuntimeError):
    """Something about an experiment's identity or place is wrong."""


# --- where -----------------------------------------------------------------

# Rebound by use_library(), the same late-binding arrangement as config.
ROOT = config.user_data_dir() / FOLDER


def resolve_root(explicit=None) -> Path:
    if explicit:
        return Path(explicit).expanduser().resolve()
    from_env = os.environ.get('CHATLENS_LIBRARY', '').strip()
    if from_env:
        return Path(from_env).expanduser().resolve()
    return (config.user_data_dir() / FOLDER).resolve()


def use_library(path) -> Path:
    global ROOT
    ROOT = Path(path).expanduser().resolve()
    return ROOT


def ensure_root() -> Path:
    ROOT.mkdir(parents=True, exist_ok=True)
    return ROOT


# --- identity --------------------------------------------------------------


def slug(name: str) -> str:
    """A folder name from what the researcher typed.

    Accents are folded rather than dropped, so "Ultimatum accentato" does not
    become "ultimatum-accentato" with a hole in the middle.
    """
    text = unicodedata.normalize('NFKD', str(name))
    text = text.encode('ascii', 'ignore').decode('ascii').lower()
    text = SLUG_SAFE.sub('-', text).strip('-')
    if text in RESERVED:
        # Windows refuses these as folder names whatever we do about it.
        text = f'{text}-experiment'
    return text[:64]


def path_for(name: str) -> Path:
    """The folder of one experiment, refusing anything outside the root.

    The slug arrives from a URL. Even though it is generated by us and matched
    against a pattern, the containment check is what actually guarantees that
    `../..` cannot become a path, so it is done rather than reasoned about.
    """
    candidate = str(name or '').strip()
    if not candidate or candidate != slug(candidate):
        raise LibraryError(f'Not an experiment name: {name!r}')

    path = (ROOT / candidate).resolve()
    try:
        path.relative_to(ROOT.resolve())
    except ValueError:
        raise LibraryError(f'Outside the library: {name!r}') from None
    return path


# --- creating and listing --------------------------------------------------


def create(name: str, adapter: str = 'generic_chat') -> Path:
    """Make an experiment and its configuration. Returns its folder."""
    from . import tomlwrite

    display = ' '.join(str(name).split())
    if not display:
        raise LibraryError('An experiment needs a name.')

    identifier = slug(display)
    if not identifier:
        raise LibraryError(
            f'"{display}" has no letters or digits to make a folder name from. '
            f'Try adding a word.'
        )

    ensure_root()
    path = path_for(identifier)
    if path.exists():
        raise LibraryError(
            f'An experiment called "{display}" already exists. '
            f'Pick another name, or open the one that is there.'
        )

    (path / 'input').mkdir(parents=True)
    (path / 'output').mkdir(parents=True)
    tomlwrite.save(
        path / 'experiment.toml',
        {'experiment': {'name': display, 'adapter': adapter}},
        header=('Written by chatlens. Editing it by hand is fine — the '
                'interface reads\nwhatever is here.'),
    )
    return path


def is_archived(path: Path) -> bool:
    return (Path(path) / ARCHIVED).exists()


def archive(name: str, archived: bool = True) -> Path:
    """Hide an experiment from the list, or bring it back.

    A marker file rather than a move or a delete: the folder stays exactly
    where it was, with everything in it, which is the difference between
    tidying a list and losing participant data.
    """
    path = path_for(name)
    marker = path / ARCHIVED
    if archived:
        marker.write_text(
            f'Archived on {datetime.now():%Y-%m-%d %H:%M}. '
            f'Delete this file to bring it back.\n', encoding='utf-8')
    elif marker.exists():
        marker.unlink()
    return path


def _last_run(path: Path):
    runs = sorted((path / 'output' / 'runs').glob('*')) if (
        path / 'output' / 'runs').is_dir() else []
    return runs[-1].name if runs else ''


def describe(path: Path) -> dict:
    """What the interface shows for one experiment."""
    from . import experiment as experiment_module

    path = Path(path)
    try:
        loaded = experiment_module.load(path)
        problem = ''
    except Exception as exc:      # noqa: BLE001 - shown, not raised
        loaded = experiment_module.Experiment()
        problem = str(exc)

    files = sorted(p for p in (path / 'input').glob('*.csv')) if (
        path / 'input').is_dir() else []
    return dict(
        slug=path.name,
        path=path,
        name=loaded.name or path.name,
        adapter=loaded.adapter,
        n_files=len(files),
        size=sum(f.stat().st_size for f in files),
        last_run=_last_run(path),
        archived=is_archived(path),
        problem=problem,
    )


def entries(include_archived: bool = False) -> list[dict]:
    """Every experiment in the library, newest activity first."""
    if not ROOT.is_dir():
        return []
    found = []
    for path in sorted(ROOT.iterdir()):
        if not path.is_dir() or path.name.startswith('.'):
            continue
        entry = describe(path)
        if entry['archived'] and not include_archived:
            continue
        found.append(entry)
    found.sort(key=lambda e: (e['last_run'], e['name']), reverse=True)
    return found
