"""Assemble the documentation site from the files people actually edit.

    python scripts/build_docs.py

The sources are the README, the illustrated guide, and the pages in
`handbook/`. Each becomes one page of the site; `docs/` holds nothing that was
written by hand and is regenerated whole. Edit a source, run this, commit both.

It used to be one source. The README carried every section and this script cut
it into sixteen pages on its numbered headings — which worked, and produced a
README of fifteen hundred lines that nobody could land on and read. The
sections are now files of their own, and splitting them is somebody's editorial
decision rather than a regular expression's.

What is left to do here is the links. On GitHub `handbook/installation.md` sits
in a folder beside the README; on the site every page is a sibling and the
folder is gone. A link left as written points at a file the site does not have,
and `mkdocs build --strict` — what CI runs — refuses to build rather than
serving it broken.
"""

from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / 'docs'
MKDOCS = ROOT / 'mkdocs.yml'
HANDBOOK = ROOT / 'handbook'

# Where a link that is not a documentation page points instead.
REPO = 'https://github.com/nicomil/chatlens'

# The order of the navigation, which is not alphabetical and not a directory
# listing: it is the order somebody meets these things. Installation before
# the analysis, the analysis before the files it writes, the troubleshooting
# last because it is looked up rather than read.
PAGES = [
    ('installation', 'Installation'),
    ('commands', 'Commands'),
    ('your-experiment', 'Your own experiment'),
    ('procedure', 'The analysis procedure'),
    ('dashboard', 'The pages in the dashboard'),
    ('files', 'The files produced'),
    ('measures', 'How the measures are built'),
    ('keys-and-costs', 'API keys, and what they cost'),
    ('topics', 'TopicGPT'),
    ('participant-data', 'Participant data'),
    ('troubleshooting', 'When something does not add up'),
    ('pilot', 'Results on the pilot'),
]


def flatten_links(text: str) -> str:
    """Point every cross-reference at the flat layout the site has."""
    # handbook/installation.md -> installation.md, anchors and all.
    text = re.sub(r'\]\(handbook/([a-z0-9-]+\.md)', r'](\1', text)
    text = text.replace('](README.md)', '](index.md)')
    text = re.sub(r'\]\(README\.md#', '](index.md#', text)
    text = text.replace('](GUIDE.md)', '](guide.md)')
    # A handbook page linking to a sibling already writes the flat form, so
    # nothing to do for those. Links out of the handbook to the root files:
    text = text.replace('](../GUIDE.md)', '](guide.md)')
    text = text.replace('](../README.md)', '](index.md)')
    # The guide writes `docs/images/...`, which is where the screenshots
    # actually are and so what GitHub needs; on the site the page is already
    # inside `docs/` and the same path would look for `docs/docs/images`.
    text = text.replace('](docs/images/', '](images/')
    # Files that belong to the repository and not to the site. They have to
    # stay relative on GitHub, where the README is read as often as here, so
    # they are sent to GitHub rather than dropped or copied in.
    for name in ('CONTRIBUTING.md', 'LICENSE'):
        text = text.replace(f']({name})', f']({REPO}/blob/main/{name})')
    return text


def title_of(text: str, fallback: str) -> str:
    for line in text.splitlines():
        if line.startswith('# '):
            return line[2:].strip()
    return fallback


def build() -> int:
    readme = ROOT / 'README.md'
    if not readme.is_file():
        print(f'{readme} not found', file=sys.stderr)
        return 1

    missing = [name for name, _t in PAGES
               if not (HANDBOOK / f'{name}.md').is_file()]
    if missing:
        print(f'Missing in {HANDBOOK}: {", ".join(missing)}', file=sys.stderr)
        return 1

    # Everything here is generated, so the folder is cleared rather than
    # merged — a page whose source was renamed would otherwise survive under
    # its old name and be served forever.
    #
    # Except the assets. Screenshots are not derived from any of the sources
    # and cannot be regenerated by this script, so a folder of them has to
    # outlive the rebuild. It has cost this project three deletions to learn
    # that; keep the exception rather than the tidiness.
    keep = {'images'}
    if DOCS.exists():
        for entry in DOCS.iterdir():
            if entry.name in keep:
                continue
            shutil.rmtree(entry) if entry.is_dir() else entry.unlink()
    DOCS.mkdir(parents=True, exist_ok=True)

    written = []

    (DOCS / 'index.md').write_text(
        flatten_links(readme.read_text(encoding='utf-8')), encoding='utf-8')
    written.append(('Home', 'index.md'))

    guide = ROOT / 'GUIDE.md'
    if guide.is_file():
        (DOCS / 'guide.md').write_text(
            flatten_links(guide.read_text(encoding='utf-8')), encoding='utf-8')
        written.append(('Guide', 'guide.md'))

    for name, fallback in PAGES:
        source = (HANDBOOK / f'{name}.md').read_text(encoding='utf-8')
        (DOCS / f'{name}.md').write_text(flatten_links(source),
                                         encoding='utf-8')
        written.append((title_of(source, fallback), f'{name}.md'))

    # Titles are quoted: "API keys, and what they cost" contains a comma, and
    # others contain colons, which YAML would read as structure.
    nav = ['nav:'] + [f'  - "{title}": {path}' for title, path in written]
    config = MKDOCS.read_text(encoding='utf-8')
    config = re.sub(r'\nnav:\n(?:  - .*\n)*', '\n' + '\n'.join(nav) + '\n',
                    config)
    MKDOCS.write_text(config, encoding='utf-8')

    print(f'{len(written)} pages in {DOCS}')
    return 0


if __name__ == '__main__':
    sys.exit(build())
